import type { Metadata } from 'next';
import './globals.css';
import ReactQueryProviders from '@/hooks/useReactQuery';

export const metadata: Metadata = {
  title: 'next',
  description: 'Generated by create next app'
};

export default function RootLayout({
  children
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <ReactQueryProviders>{children}</ReactQueryProviders>
      </body>
    </html>
  );
}
